import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main course sidebar with all 18 chapters organized by topic
  courseSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Part I: Foundations',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01-introduction',
        },
        {
          type: 'autogenerated',
          dirName: '02-intelligent-machines',
        },
        {
          type: 'autogenerated',
          dirName: '03-robot-sensing',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part II: ROS 2 & Simulation',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '04-ros2-basics',
        },
        {
          type: 'autogenerated',
          dirName: '05-ros2-programming',
        },
        {
          type: 'autogenerated',
          dirName: '06-simulation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part III: Robot Modeling & Physics',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '07-robot-models',
        },
        {
          type: 'autogenerated',
          dirName: '08-robot-physics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part IV: Advanced Simulation',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '09-nvidia-isaac',
        },
        {
          type: 'autogenerated',
          dirName: '10-vision-mapping',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part V: Humanoid Robotics',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '11-humanoid-movement',
        },
        {
          type: 'autogenerated',
          dirName: '12-walking-balance',
        },
        {
          type: 'autogenerated',
          dirName: '13-manipulation-interaction',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part VI: AI Integration',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '14-vla',
        },
        {
          type: 'autogenerated',
          dirName: '15-talking-robots',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part VII: Hardware & Deployment',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '16-hardware',
        },
        {
          type: 'autogenerated',
          dirName: '17-sim-to-real',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part VIII: Final Project',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '18-final-project',
        },
      ],
    },
    {
      type: 'doc',
      id: 'glossary',
      label: 'Glossary',
    },
  ],
};

export default sidebars;
